### PR TITLE
close #54 by using GitHub corner to link to this repository

### LINKED ISSUE #54: feat: change link to GitHub from this repository's website into a GitHub corner
I think it would be neat if instead of linking to this repository with a hyperlink from [this repository's website](https://jamiebuilds.github.io/tinykeys/), we used a [GitHub corner](https://tholman.com/github-corners/), instead.

### PR DESCRIPTION
**Pull request by hamirmahal**
This pull request closes #54 if merged. It removes the text link to this repository's website with a GitHub corner.﻿

### CODE REVIEW

**Comment by hamirmahal** [comment]
Current appearance, without merging this pull request:

Screen Shot 2020-11-12 at 11 19 09 AM

Appearance if we merge this pull request:

Screen Shot 2020-11-12 at 11 20 05 AM

**Comment by hamirmahal** [comment]
@jamiebuilds do you think this is worth adding? I really enjoy the repository, by the way; thanks for creating it.

**Comment by jamiebuilds** [comment]
thanks!

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
